src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Card</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HospitalManagementController.cls
public class HospitalManagementController {
String contactId; 
List <Payment__C> pmt = new List<Payment__C>();
public String paymentMode{get;set;}
public Date paymentDate {get;set;}
public Decimal paymentAmount {get;set;}

    public HospitalManagementController(ApexPages.StandardController controller) {
    contactId  = ApexPages.currentPage().getParameters().get('id');
    if(contactId!=null)
        pmt = [select Payment_Amount__c,Payment_Date__c,Payment_Mode__c, Patient__c from Payment__C where Patient__c =: contactId]; 
        paymentMode = pmt[0].Payment_Mode__c;
        paymentDate = pmt[0].Payment_Date__c;
        paymentAmount  = pmt[0].Payment_Amount__c;
              }  


}